name: Java CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Tests
        run: npm test
