name: Java CI

on:
   push:
      branches:
        - main
      workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Print test results
        if: failure()  # This step will run only if the previous steps fail
        run: cat /home/runner/work/TP_homework_2/TP_homework_2/target/surefire-reports/*.txt
      - name: Send Telegram notification on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "✅ Тесты успешно пройдены! - ${{ github.repository }} @ ${{ github.ref }}"
      - name: Send Telegram notification on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "❌ Тесты не пройдены! - ${{ github.repository }} @ ${{ github.ref }}"