name: Java CI

on:
   push:
      branches:
        - main
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Print test results
        if: failure()
        run: cat /home/runner/work/TP_homework_2/TP_homework_2/target/surefire-reports/*.txt
      - name: Send Telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ job.status == 'success' && '✅ Тесты успешно пройдены' || '❌ Некоторые тесты не пройдены' }}
            ${{ job.status != 'success' && '\n + steps.test.outputs.failures + '\n || '' }}